version: "3.9"

services:
  entrypoint:
    build:
      context: ./entrypoint

    cap_add:
      - NET_ADMIN
      - NET_RAW
    sysctls:
      net.ipv4.ip_forward: 0
    cpus: ${ENTRYPOINT_LIMIT_CPU:-0.3}
    mem_limit: ${ENTRYPOINT_LIMIT_MEM:-128m}

    networks:
      network:

  server1:
    build:
      context: ./server1

    restart: unless-stopped
    cpus: ${SERVER_LIMIT_CPU:-0.01}
    mem_limit: ${SERVER_LIMIT_MEM:-8m}

    environment:
      FLAG: flag-12ec5c6dcb790868b67e8ed15dac2122f462f1f88b290fb04ef3778bdb2a9d83
      FLAG_INTERVAL: ${FLAG_INTERVAL:-60}

    networks:
      network:

  server2:
    build:
      context: ./server2

    restart: unless-stopped
    cpus: ${SERVER_LIMIT_CPU:-0.01}
    mem_limit: ${SERVER_LIMIT_MEM:-8m}

    networks:
      network:

networks:
  network:
    driver_opts:
      com.docker.network.bridge.name: ${BR_NAME:-np-level3}
