#!/bin/ash
# This script builds the levels ahead of time
set -e

for LEVEL in $(find /levels -mindepth 1 -maxdepth 1 -type d | sort -V); do
  LEVEL_NAME=$(basename "$LEVEL")
  echo "info: building '$LEVEL_NAME'" 

  cd "$LEVEL"
  docker compose build &>/dev/null
done
