version: "3.9"

services:
  entrypoint:
    build:
      context: ./entrypoint

    cap_add:
      - NET_ADMIN
      - NET_RAW
    sysctls:
      net.ipv4.ip_forward: 0
    cpus: ${ENTRYPOINT_LIMIT_CPU:-0.3}
    mem_limit: ${ENTRYPOINT_LIMIT_MEM:-128m}

    networks:
      network:

  server1:
    build:
      context: ./server1

    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    cpus: ${SERVER_LIMIT_CPU:-0.01}
    mem_limit: ${SERVER_LIMIT_MEM:-8m}

    volumes:
      - common:/common

    environment:
      FLAG: flag-7b7fa4c1a75a2e95f3f9aa8a5307af8412c0f76847710ba04f08a642d0909fb5

    networks:
      network:

  server2:
    build:
      context: ./server2

    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    cpus: ${SERVER_LIMIT_CPU:-0.01}
    mem_limit: ${ENTRYPOINT_LIMIT_MEM:-8m}

    volumes:
      - common:/common

    environment:
      FLAG_INTERVAL: ${FLAG_INTERVAL:-60}

    networks:
      network:

  server3:
    build:
      context: ./server3

    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    cpus: ${SERVER_LIMIT_CPU:-0.01}
    mem_limit: ${SERVER_LIMIT_MEM:-8m}

    networks:
      network:

volumes:
  common:

networks:
  network:
    driver_opts:
      com.docker.network.bridge.name: ${BR_NAME:-np-level5}
